// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Read provides a mock function with given fields: startPos, buf
func (_m *Reader) Read(startPos uint, buf []byte) int {
	ret := _m.Called(startPos, buf)

	var r0 int
	if rf, ok := ret.Get(0).(func(uint, []byte) int); ok {
		r0 = rf(startPos, buf)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewReader creates a new instance of Reader. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewReader(t testing.TB) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
